-- CRIAÇÃO DA TABELA DE TÉCNICOS
-- Baseado no arquivo src/data/collaborators.ts

CREATE TABLE IF NOT EXISTS public.technicians (
    login text PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS (Segurança)
ALTER TABLE public.technicians ENABLE ROW LEVEL SECURITY;

-- Política de Leitura Pública (para o sistema poder consultar)
CREATE POLICY "Technicians are public read" ON public.technicians FOR SELECT USING (true);

-- Política de Escrita Apenas Admin (Opcional, mas seguro)
CREATE POLICY "Admins can manage technicians" ON public.technicians 
    USING (auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin'));

-- INSERÇÃO DE DADOS (MIGRATION)
INSERT INTO public.technicians (login, name, email) VALUES
('N5780198', 'ALZINETE BEZERRA DA SILVA', 'Alzinete.Silva@claro.com.br'),
('N4014011', 'ALAN MARINHO DIAS', 'Alan.Dias@claro.com.br'),
('N5964627', 'LUIZ FERREIRA DA SILVA', 'Luiz.Silva4f95e@claro.com.br'),
('F101453', 'ANDREA SEBASTIANA RODRIGUES', 'ANDREA.RODRIGUES@claro.com.br'),
('N5691268', 'ANGELITA MARIA FIGUEIREDO NOGUEIRA', 'Angelita.Nogueira@claro.com.br'),
('N0051944', 'CLAUDIO HENRIQUES ARAUJO', 'Claudio.HAraujo@claro.com.br'),
('N6172219', 'CLAUDIA SANTOS DA SILVA', 'Claudia.Silva2@claro.com.br'),
('F117877', 'CLAUDILENE SILVA GONCALVES', 'claudilene.goncalves@claro.com.br'),
('F117879', 'GABRIELE SIMM DE ALMEIDA', 'gabriele.almeida@claro.com.br'),
('N5754357', 'GISELE COSTA DE SANT ANA AZEVEDO', 'Gisele.ana@claro.com.br'),
('F250585', 'JULIA SILVA WANDERLEY RIBEIRO', 'julia.silviaribeiro@claro.com.br'),
('F119335', 'DEBORAH VIEIRA FRANCA LAURENTINO', 'deborah.laurentino@claro.com.br'),
('N5927605', 'LEANDRO DA SILVA', 'Leandro.Silva5@claro.com.br'),
('N6172324', 'LEANDRO DOS SANTOS PEREIRA DOS SANTOS', 'Leandro.PereiraSantos@claro.com.br'),
('N5711056', 'ELIDA BATISTA DE LIMA', 'Elida.Lima@claro.com.br'),
('N5755480', 'ERIKA CONCEICAO DOS SANTOS', 'Erika.Santos3@claro.com.br'),
('F120501', 'JAKEISE KARLA DO NACIMENTO', 'jakeise.nacimento@claro.com.br'),
('N5937193', 'BRUNO HENRIQUE DE AQUINO', 'bruno.aquino@claro.com.br'),
('N6027115', 'LARISSA SOUZA CARVALHO', 'Larissa.Carvalho@claro.com.br'),
('F104784', 'PHILIPE SILVA FARIAS', 'philipe.farias@claro.com.br'),
('N0091918', 'CAMILA MARCONDES GARCEZ', 'Camila.Garcez@claro.com.br'),
('N5654131', 'CARLA CAROLINE DE AQUINO GOMES', 'Carla.Aquino@claro.com.br'),
('N6111746', 'LUCIANA SILVA DE OLIVEIRA', 'Luciana.Oliveira4@claro.com.br'),
('T1494870', 'THAILANE FAGUNDES GONCALVES ROSA', 'thailane.goncalves@claro.com.br'),
('N0158974', 'CARLOS EDUARDO BARRETO DE ABREU', 'Carlos.BarretoAbreu@claro.com.br'),
('N5693151', 'RAFAEL DAVID GARCIA', 'Rafael.Garcia4@claro.com.br'),
('N5934323', 'VANESSA MACEDO ZORANTE LYRA', 'Vanessa.Lyra@claro.com.br'),
('N0136536', 'SAULO COSTA LOPES', 'Saulo.Lopes@claro.com.br'),
('N5748944', 'THIAGO MATTOS PARAMOS', 'Thiago.Paramos@claro.com.br'),
('N5650628', 'ANDERSON GARCIA RODRIGUES', 'Anderson.Rodrigues2@claro.com.br'),
('N5972428', 'CRISTIANE HERMOGENES DA SILVA', 'Cristiane.Silva4@claro.com.br'),
('N0150817', 'ALEXANDRE SAMPAIO DE OLIVEIRA', 'Alexandre.Sampaio@claro.com.br'),
('N5604148', 'DANIEL MARCELO FELISBERTO OLIVEIRA', 'Oliveira.MDaniel@claro.com.br'),
('N5734436', 'EVELYN DA SILVA', 'evelyn.silva@claro.com.br'),
('NLSOARE', 'NELSON LEANDRO SOARES', 'NLSOARE@embratel.com.br'),
('N0034439', 'DIEGO NUNES BANDEIRA', 'Diego.Bandeira@claro.com.br'),
('N5768308', 'PATRICK SARMENTO CARNEIRO TAVARES', 'Patrick.Tavares@claro.com.br'),
('N5646768', 'EDUARDO ARAUJO GARCIA', 'Eduardo.Garcia2@claro.com.br'),
('F196463', 'EDUARDO CUNHA PONTES', 'eduardo.pontes@claro.com.br'),
('TPAROLI', 'THIAGO PAROLI DE MENDONCA', 'TPAROLI@embratel.com.br'),
('N5619600', 'BRUNO COSTA BUCARD', 'Bruno.Bucard@claro.com.br'),
('N5946649', 'JULIANA SANTOS DO AMARAL FUSANI', 'juliana.amaral2@claro.com.br'),
('N5925243', 'LUCAS CARDOSO SANTOS SILVA', 'Lucas.CardosoSilva@claro.com.br'),
('F201714', 'FERNANDA MESQUITA DE FREITAS', 'fernanda.mesquita@claro.com.br'),
('N0017089', 'ERIKA ELYSYENE ALVES NOGUEIRA', 'Erika.Massena@claro.com.br'),
('N5956034', 'EVANDRO SOARES MENEZES', 'Evandro.Menezes@claro.com.br'),
('N5812006', 'MAGNO FRANCA ASSIS', 'Magno.Assis2@claro.com.br'),
('F118491', 'MARCELO LUIS DOS SANTOS JUNIOR', 'marcelo.luis@claro.com.br'),
('F236454', 'MARIA CLARA NASCIMENTO GOMES', 'maria.claragomes@claro.com.br'),
('N5713690', 'GABRIELA TAVARES DA SILVA', 'Gabriela.Silva3@claro.com.br'),
('F250588', 'MELISSA GUIMARAES GITAHY', 'melissa.gitahy@claro.com.br'),
('N5816648', 'MICHAEL BARBOSA DE SOUSA', 'Michael.Sousa@claro.com.br'),
('N0189105', 'IGOR MARCELINO DE MARINS', 'Igor.Marins@claro.com.br'),
('N5708231', 'TATIANA GONZAGA DOS SANTOS', 'Tatiana.gonzagaSantos@claro.com.br'),
('F193194', 'GABRIEL PEREIRA RODRIGUES', 'gabriel.rodrigues2@claro.com.br'),
('N5927655', 'THIAGO RIBEIRO DE ALMEIDA', 'Thiago.RibeiroAlmeida@claro.com.br'),
('LGCARVA', 'LEANDRO GONCALVES DE CARVALHO', 'LGCARVA@embratel.com.br'),
('N5931474', 'FABIO ALMEIDA DE SOUSA', 'Fabio.Sousa3@claro.com.br'),
('N0238475', 'MARLEY MARQUES RIBEIRO', 'Marley.Ribeiro@claro.com.br'),
('N5932064', 'MONICA DA SILVA RODRIGUES', 'Monica.Rodrigues@claro.com.br'),
('N0125317', 'ROBERTO SILVA DO NASCIMENTO', 'Roberto.SilvaNascimento@claro.com.br'),
('F251398', 'IZABELA MARTINS CARNEIRO DE ASSIS', 'izabela.assis@claro.com.br'),
('N5819183', 'RODRIGO PIRES BERNARDINO', 'rodrigo.bernardino@claro.com.br'),
('N5927887', 'FLAVIO ALVES DA COSTA', 'Flavio.Costa4@claro.com.br'),
('N6173055', 'JEFFERSON LUIS GONCALVES COITINHO', 'Jefferson.Coitinho@claro.com.br'),
('LEOCOEM', 'LEONARDO COELHO DE MACEDO', 'leonardo.macedo@claro.com.br'),
('N5923996', 'JULIO CESAR SANTOS SOARES', 'Julio.SantosSoares@claro.com.br'),
('N0057998', 'CLAUDIO PRALON RODRIGUES', 'Claudio.Pralon@claro.com.br'),
('F247715', 'NELCI STOFEL', 'nelci.stofel@claro.com.br'),
('N5926003', 'SUELLEN HERNANDEZ DA SILVA', 'suellen.hernandez@claro.com.br'),
('F201801', 'ADRIANO BOAS NASCIMENTO', 'adriano.nascimento2@claro.com.br'),
('N5577632', 'ALINE LOURENCO ALVES ANDRADE', 'Andrade.LAline@claro.com.br'),
('N0223834', 'PATRICIA DA SILVA', 'Silva.SPatricia@claro.com.br'),
('F106664', 'RAISSA LIMA DE OLIVEIRA', 'raissa.loliveira@claro.com.br'),
('F117873', 'ANDRESSA CARVALHO BARRETO LOUCHARD', 'andressa.barreto@claro.com.br'),
('N0239871', 'LEONARDO FERREIRA LIMA DE ALMEIDA', 'Leonardo.LimaAlmeida@claro.com.br'),
('N5565237', 'ANTONIO CLELTON FILHO', 'Filho.CAntonio@claro.com.br'),
('F118457', 'LUCAS ALVES DA SILVA', 'lucas.alvessilva@claro.com.br'),
('N6028389', 'THAIS ATAIDE BARRETO', 'Thais.Barreto@net.com.br'),
('N5775686', 'ELIAS DA SILVA DE GOBBI', 'elias.gobbi@claro.com.br'),
('N5577797', 'LUCIMARA MOSQUEIRA PIZAO', 'Lucimara.Pizao@claro.com.br'),
('N6105199', 'GREGORI LIMA DE SOUZA', 'GREGOLS@embratel.com.br'),
('F119540', 'ALEXANDRE XAVIER DE SOUZA', 'alexandre.xaviersouza@claro.com.br'),
('F106663', 'AMANDA DOS SANTOS SILVA', 'amanda.dssilva@claro.com.br'),
('F105097', 'CAIO LUCIDI BOURGUIGNON', 'caio.bourguignon@claro.com.br'),
('MROSILVA', 'MARCOS ROGERIO DA SILVA', 'marcos.rogerio@claro.com.br'),
('N5927784', 'ELIZANGELA DE SOUZA RABELO', 'Elizangela.Rabelo@claro.com.br'),
('N6027086', 'ERIKA ALBUQUERQUE DIAS', 'Erika.Dias@claro.com.br'),
('N5577565', 'MARISTELLA MARCIA DOS SANTOS', 'Maristella.Santos@claro.com.br'),
('N6070655', 'JULIANA RODRIGUES MOREIRA ORLANDO', 'JULIRM@embratel.com.br'),
('N5705734', 'MICHELE GUARANHO ANSELMO PEREIRA', 'Michele.Pereira@claro.com.br'),
('N5973848', 'SANDRO BREIA DE FARIA', 'Sandro.Faria@claro.com.br'),
('F196679', 'PHELIPE PACHECO DE CARVALHO', 'phelipe.carvalho@claro.com.br'),
('F101864', 'TATIANE COSTA DURVAL', 'TATIANE.DURVAL@claro.com.br'),
('N0067383', 'RAPHAEL DE MELO FERREIRA', 'Raphael.Ferreira@claro.com.br'),
('N0223133', 'ANDREZA DE FREITAS MANZONI RAMOS', 'Andreza.Ramos@claro.com.br'),
('N5695123', 'SIMONE ASSIS DA COSTA', 'Simone.Costa2@claro.com.br'),
('F101976', 'TAYLISSA ELOIZA ROSA MESSIAS', 'TAYLISSA.MESSIAS@claro.com.br'),
('N0188709', 'MARCOS SOUZA DE JESUS', 'Marcos.SouzaJesus@claro.com.br'),
('N5962760', 'VINICIUS PIMENTEL FERNANDES', 'Vinicius.Fernandes@claro.com.br'),
('N0014611', 'RAFAEL ECCARD DA SILVA', 'Rafael.Eccard@claro.com.br'),
('N5972923', 'ANDRE LOURENCO DA SILVA', 'Andre.LourencoSilva@claro.com.br'),
('N5724716', 'ARMANDO PEREIRA DUARTE', 'Armando.Duarte@claro.com.br'),
('N6088602', 'REGINA DE AZEVEDO GOMES MARQUES', 'RAGMARQ@embratel.com.br'),
('F218860', 'ALDENES MARQUES IDALINO DA SILVA', 'aldenes.silva@claro.com.br'),
('F201734', 'BRENDA FERNANDA DA SILVA DAVID', 'brenda.david@claro.com.br'),
('N6026848', 'BRUNO RIBEIRO ARAUJO', 'Bruno.Araujo3@claro.com.br'),
('N5969641', 'CARLOS ALEXANDRE COSTA DE OLIVEIRA', 'Carlos.Oliveira4@claro.com.br'),
('N5941223', 'ROSANA RIEGER MATOS', 'Rosana.Matos@claro.com.br'),
('N5957832', 'ROSEMARY ARRUDA GONCALVES', 'Rosemary.Goncalves@claro.com.br'),
('N4025723', 'CLAUDIA CARLA BARROS DOS SANTOS', 'Claudia.BarrosSantos@claro.com.br'),
('N5737414', 'SANDRO DA SILVA CARVALHO', 'Sandro.SilvaCarvalho@claro.com.br'),
('N6172922', 'DJALMIR SILVA DE SENA', 'Djalmir.Sena@claro.com.br'),
('N5946041', 'FABIO ANGELO MAGELA DE ALMEIDA', 'Fabio.Almeida3@claro.com.br'),
('N5931149', 'DANIEL SOUZA DA SILVA', 'Daniel.Silva5@claro.com.br'),
('N5739694', 'GUILHERME SCALON DA SILVA COELHO', 'Guilherme.Coelho@claro.com.br'),
('N5772610', 'FABIO DE OLIVEIRA MIRANDA', 'Fabio.Miranda2@claro.com.br'),
('N5923221', 'KELLY PINHEIRO LIRA', 'Kelly.Lira@claro.com.br'),
('N5932208', 'KETLIN MACIELE DOS SANTOS TEIXEIRA ROCHA', 'Ketlin.Rocha@claro.com.br'),
('F119481', 'LAYSSA MENDES DE LIMA', 'layssa.lima@claro.com.br'),
('N5772086', 'THIAGO PEREIRA DA SILVA', 'Thiago.Silva2@claro.com.br'),
('N5946675', 'LEONARDO GARCIA CHACON PEREIRA SILVA', 'Leonardo.Silva6@claro.com.br'),
('N5802257', 'MAGNO FERRAREZ DE MORAIS', 'Magno.Morais2@claro.com.br'),
('N5963374', 'THIAGO RODRIGUES LOPES', 'Thiago.Lopes2@claro.com.br'),
('N5705710', 'ULYSSES FERREIRA DOS SANTOS', 'Ulysses.Santos@claro.com.br'),
('F194004', 'ROBERTA MATHEUS DE SOUZA', 'roberta.matheus@claro.com.br'),
('N5791719', 'MICHEL MEDEIROS GOMES', 'michel.gomes@claro.com.br'),
('N5755246', 'THIAGO SPINELLI MOTTA', 'Thiago.Motta2@claro.com.br'),
('F251397', 'YAN RIBEIRO DE BARROS LIMA', 'yan.lima@claro.com.br'),
('F204779', 'Anderson Alves Pereira', 'anderson.pereira3@claro.com.br'),
('F139720', 'ANDRESSA DA SILVA CANTELLI', 'andressa.cantelli@claro.com.br'),
('F201521', 'CLAUDILENE ALINE TEIXEIRA', 'claudilene.teixeira@claro.com.br'),
('N0150881', 'CRISTIANO FELIZARDO GONCALVES', 'cristiano.goncalves@claro.com.br'),
('F203616', 'DANIELI DA SILVA XAVIER', 'danieli.xavier@claro.com.br'),
('N5789651', 'Diego Fortes Machado', 'diego.fortes@claro.com.br'),
('N5692365', 'GABRIEL RICARDO BRAGA', 'Gabriel.Lima@claro.com.br'),
('N6193201', 'KENIDY MESQUITA PEREIRA', 'kenidy.pereira@claro.com.br'),
('N5925669', 'KESSE WENDEL GONCALVES VIEIRA', 'kesse.vieira@claro.com.br'),
('F238708', 'LISIANE RODRIGUES DA SILVA', 'lisiane.silva@claro.com.br'),
('F118499', 'PATRIK PEREIRA DOS SANTOS', 'patrik.santos@claro.com.br'),
('N0113194', 'RENATO GROSS DOS SANTOS', 'renato.gross@claro.com.br'),
('F272649', 'DAVID VILA NOVA DE LIMA', 'david.lima@claro.com.br'),
('F265309', 'HELLITON DOS SANTOS SILVA', 'helliton.silva@claro.com.br'),
('F227005', 'IAZIR IAM PEREIRA DOS SANTOS', 'iazir.santos@claro.com.br'),
('F236059', 'Kelson Ricardo Cruz Macedo', 'kelson.macedo@claro.com.br'),
('F249222', 'BIANCA LOPES LEMOS', 'bianca.lemos@claro.com.br'),
('F282772', 'JOAO GABRIEL DE ALMEIDA FERREIRA', 'joao.gabrielferreira@claro.com.br'),
('F196369', 'DEBORA CRISTINA DE OLIVEIRA', 'f260187@brasilcenter.com.br'),
('F196368', 'LAUS SANTOS ARAUJO', 'f196368@brasilcenter.com.br'),
('F247793', 'LEANDRO AMARO RODRIGUES', 'f247793@brasilcenter.com.br'),
('F254909', 'AMANDA CARVALHO DE PAIVA', 'f254909@brasilcenter.com.br'),
('F254908', 'HUGO DO PRADO XAVIER DE OLIVEIRA', 'F254908@brasilcenter.com.br'),
('F276023', 'JOANA NAYARA SILVA DE OLIVEIRA', 'F276023@brasilcenter.com.br'),
('F276611', 'TANIA FERREIRA LEMOS', 'F276611@brasilcenter.com.br'),
('F277138', 'SIWENE SAORY HOKAMA OTOBONI', 'F277138@brasilcenter.com.br'),
('F277822', 'PATRICK ANTONIO SERAFIM PAVANELLI', 'F277822@brasilcenter.com.br'),
('F196378', 'GENIELMA GAMA DA SILVA ARAUJO', 'F196389@brasilcenter.com.br'),
('F280483', 'LIVIA RODRIGUES SILVA', 'livia.rsilva@brasilcenter.com.br'),
('F260187', 'ANDERSON GUIMARAES FERREIRA', 'f260187@brasilcenter.com.br'),
('F277124', 'ALINE LABAKI', 'F277124@brasilcenter.com.br'),
('F277171', 'RAI SANTOS DE OLIVEIRA', 'F277171@brasilcenter.com.br'),
('F277140', 'JULIA RODRIGUES DE SOUZA', 'F277140@brasilcenter.com.br'),
('F205082', 'ELDINE MEIRA COUTINHO', 'F277124@brasilcenter.com.br'),
('F183107', 'RAFAEL DOS SANTOS', 'f183107@brasilcenter.com.br'),
('F280585', 'ARIANE CRISTIANE FONSECA DE SOUZA', 'F280585@brasilcenter.com.br'),
('F282166', 'SHEILA CAROLINA DA SILVA', 'F282166@brasilcenter.com.br'),
('F282187', 'VITORIA LAURA RODRIGUES ALVES FERREIRA', 'F282187@brasilcenter.com.br'),
('N0184868', 'GUILHERME HENRIQUE APELT DE QUEVEDO FERREIRA', 'Guilherme.Quevedo@claro.com.br'),
('N5813452', 'SAMUEL TARCIO DOS SANTOS DE BRITO', 'Samuel.Brito@claro.com.br'),
('F118475', 'TAYLON WILLIAN MARINHO DE LIMA', 'taylon.lima@claro.com.br'),
('F182906', 'JESSI FERNANDA GOMES', 'jessi.gomes@claro.com.br'),
('N4011863', 'LUCAS VIEIRA NOBLE', 'Lucas.VieiraNoble@claro.com.br'),
('N5943910', 'ELISEU GOULART DE MELO', 'Eliseu.Melo@claro.com.br'),
('F102691', 'EDIVAL MIZUNO', 'edival.mizuno@claro.com.br'),
('N5775741', 'FALZER GABRIEL PIRES FRANCISCO', 'Falzer.Francisco@claro.com.br'),
('f107952', 'LEONARDO TESSAROLO FASSA', 'leonardo.fassa@claro.com.br'),
('F104752', 'MARCELO DE SOUZA ALMEIDA', 'marcelo.salmeida@claro.com.br'),
('F120931', 'MARCELO VENERI JUNIOR', 'marcelo.junior2@claro.com.br'),
('F152611', 'MARCOS INOCENCIO DE AGUIAR', 'marcos.aguiar@claro.com.br'),
('F104882', 'NATALIA BRAGA MARTINS', 'natalia.martins@claro.com.br'),
('N4019516', 'RAFAEL DA SILVA GONÇALVES', 'Rafael.SilvaGoncalves@claro.com.br'),
('N5963881', 'TIAGO ALMEIDA TIBURCIO DE SOUZA', 'Tiago.souza3@claro.com.br'),
('QGINASI', 'FLAVIA REGINA DE LUCCA SIQUEIRA', 'qginasi@brasilcenter.com.br'),
('F249209', 'GRACE SAUANA DA SILVA ARAUJO', 'F249209@brasilcenter.com.br'),
('N5591078', 'TALITA DE LUNA LACERDA GUSTINELLI', 'TALITA.DELUNALACERDAGUSTINELLI@claro.com.br')
ON CONFLICT (login) DO UPDATE SET 
    email = EXCLUDED.email,
    name = EXCLUDED.name;
