export interface Incident {
    // Database ID (will be generated by Supabase, but useful for frontend state)
    id: string;

    // Imported fields
    indicador_nome_icg: string;
    id_mostra: string;
    volume: number;
    indicador: string;
    indicador_status: string;
    in_regional: string;
    in_grupo: string;
    in_cidade_uf: string;
    in_uf: string;
    tecnologia: string;
    servico: string;
    natureza: string;
    sintoma: string;
    ferramenta_abertura: string;
    fechamento: string;
    solucao: string;
    impacto: string;
    enviado_toa: string;
    dt_inicio: string; // ISO string or format from excel
    dt_inicio_sistema: string;
    dt_inicio_chegou_cop_fo: string;
    dt_em_progresso: string;
    dt_designado: string;
    dt_primeiro_acionamento_rf: string;
    dt_primeiro_acionamento_fo: string;
    dt_primeiro_acionamento_gpon: string;
    dt_fim: string;
    dt_fim_sistema: string;
    dt_fim_sistema_primeiro_fechamento: string;
    tma: string | number;
    tmr: string | number;
    anomes: string | number;

    // Audit fields (enriched)
    status_audit?: 'Pendente' | 'Tratado';
    audit_corrigido?: boolean;
    audit_login?: string;
    audit_motivo?: string;
    audit_evidencia_url?: string;
    audit_login_ofensor?: string;
    audit_updated_at?: string;
    created_at?: string;
}
